image:
  file: .gitpod.Dockerfile

ports:
  - port: 31337 # npmgraph web preview
    visibility: public
tasks:
  - init: npm install && npm run build
    command: >
      npm run start
      # gp preview localhost:31337#/view/2d/%2540theia%252Ftask
